### ISSUE TITLE
Support custom cargo arguments

### ISSUE THREAD

**Issue by 7sDream** [cmyr/RustPlayground#17]
Sometimes I want compile a short section code in `release` mode and measure its performance, and Rust Playground is a greate tools to do it.

But current I can't find a way to pass the `--release` argument to cargo when compile code.

Is there any possibility to add this feature?

**Comment by cmyr** [comment]
@7sDream I believe `cargo instruments --release ...` will do a release build with debug symbols, let me know if this doesn't seem to be working?

You can see supported arguments with `cargo help instruments`.

**Comment by 7sDream** [comment]
Yes it works, but, emmmm, this issue is opened in RustPlayground repo, not cargo-instruments.

😄️

**Comment by cmyr** [comment]
haha oops. Yes, it looks like this feature is not currently available. It shouldn't be too hard to add; I'd probably do it as a selectable menu item in the `Cargo` menu. If you're interested you're welcome to look into this, or I can take a look when I have some time, although I'm not sure when that would be. 😬

**Comment by 7sDream** [comment]
Sadly, I'm not familiar with neither Swift language nor macOS App development.

But I can try learn them and add this feature if I'm not busy in this weekend.

**Comment by cmyr** [comment]
Okay, I've added a menu item that will do this. I'm not sure when I'll get around to doing a release, but if you have Xcode installed, you can do `xcodebuild` from the command line to build a new app bundle.

**Comment by 7sDream** [comment]
It works like a charm, thank you!
