### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by Milo123459** [cmyr/RustPlayground#23]

**Comment by cmyr** [comment]
This is not planned, although you are welcome to do a port!

**Comment by Milo123459** [comment]
Iirc there is a swift for windows type thing?

**Comment by cmyr** [comment]
swift the language may run on windows, but this project uses the AppKit SDK that is macOS only; a port would be a fairly substantial task, and would involve reimplementing all of the macos-specific code (that is, everything in the RustPlayground directory) in this project for windows.

**Comment by Milo123459** [comment]
Oh!
