### ISSUE TITLE
Building from source and libplayground.a can't be found

### ISSUE THREAD

**Issue by jspencer** [cmyr/RustPlayground#6]
I wasn't able to build from source out of the box.

For anyone with the same issue, the error was:
`error: [...]/RustPlayground/playground-utils-ffi/target/libplayground.a: No such file or directory`

I had to re-add the file in the Copy Files Phase in the Xcode project. I am guessing a pull request containing my changes to project.pbxproj wouldn't be very useful (and mine is not necessarily the best solution), but the operative change was changing `path = "../playground-utils-ffi/target/libplayground.a";` to `path = "../playground-utils-ffi/target/release/libplayground.a";` 

This is a fun project, thanks for making it!

**Comment by cmyr** [comment]
@jspencer I did have an issue here that was fixed in 93c2dd6; do you have that commit?

**Comment by jspencer** [comment]
Yes, I'm up to date and have that commit. 

It works if I add the copy that is in the "install" action, but missing from the "build" action. That is instead of the change I'd suggested above.

`cp "${OUTDIR}/${RUST_CONFIGURATION}/${PRODUCT_NAME}" "${OUTDIR}/${PRODUCT_NAME}"`

**Comment by cmyr** [comment]
huh, weird, I'll play around a bit more.

**Comment by cmyr** [comment]
@jspencer would you like to check and see if #7 resolves this for you?

**Comment by jspencer** [comment]
Yes, that fixed it for me. Thanks
